### ISSUE TITLE
cannot import name lru_cache

### ISSUE THREAD

**Issue by Maryam-Imani** [openeventdata/mordecai#43]
>>> import mordecai
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mordecai/__init__.py", line 1, in <module>
    from .geoparse import Geoparser
  File "/usr/local/lib/python2.7/dist-packages/mordecai/geoparse.py", line 7, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache

I am not sure, but the version of this package on my computer might be different from you. Mine is: 
backports.functools-lru-cache==1.4
functools32==3.2.3.post2

**Comment by ahalterman** [comment]
The error seems to come from trying to run Mordecai with Python 2. I've only tested it with 3. It now tries to import the Python2 version of `lru_cache` on `ImportError`, but there are still a number of potential Python2 issues and I'd recommend just using 3 with it.

**Comment by Maryam-Imani** [comment]
I also tried Python3. I got the following errors: 

>>> import mordecai 
Using TensorFlow backend.
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.13.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mordecai/__init__.py", line 1, in <module>
    from .geoparse import Geoparser
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 11, in <module>
    from . import utilities
  File "/usr/local/lib/python3.5/dist-packages/mordecai/utilities.py", line 12, in <module>
    import spacy
  File "/usr/local/lib/python3.5/dist-packages/spacy/__init__.py", line 4, in <module>
    from .cli.info import info as cli_info
  File "/usr/local/lib/python3.5/dist-packages/spacy/cli/__init__.py", line 1, in <module>
    from .download import download
  File "/usr/local/lib/python3.5/dist-packages/spacy/cli/download.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python3.5/dist-packages/requests/__init__.py", line 90, in <module>
    from urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'

**Comment by ahalterman** [comment]
What happens if you do `pip3 install --upgrade urllib3`?

**Comment by Maryam-Imani** [comment]
I got this:

>>> import mordecai 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mordecai/utilities.py", line 15, in <module>
    nlp
NameError: name 'nlp' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/mordecai/__init__.py", line 1, in <module>
    from .geoparse import Geoparser
  File "/usr/local/lib/python3.5/dist-packages/mordecai/geoparse.py", line 11, in <module>
    from . import utilities
  File "/usr/local/lib/python3.5/dist-packages/mordecai/utilities.py", line 17, in <module>
    nlp = spacy.load('en_core_web_lg')
  File "/usr/local/lib/python3.5/dist-packages/spacy/__init__.py", line 19, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.5/dist-packages/spacy/util.py", line 119, in load_model
    raise IOError("Can't find model '%s'" % name)
OSError: Can't find model 'en_core_web_lg'

**Comment by ahalterman** [comment]
Sounds like it fixed the previous error. That error comes from the spaCy NLP model not being installed (issue #39 describes about how it's not installed with `setup.py`). I'll add a better error message if that happens. In the mean time, try 

```
python -m spacy download en_core_web_lg
```

**Comment by Maryam-Imani** [comment]
Now, it is working. Thanks.
