### ISSUE TITLE
Fresh installation can't import Geoparser

### ISSUE THREAD

**Issue by thomas-hervey** [openeventdata/mordecai#70]
After a fresh install and using _pyenv_ and _pipenv_ to manage my python version and pip packages, I've tried running the example usage but I receive the ImportError "Cannot import name Geoparser". I've tried running and installing Mordecai using both Python2 and Python3.

Any way to easily check what can be imported from Mordecai? Forgive me if this is a Python misunderstanding and not a Mordecai issue.

---
In my working directory...
.python-version
```
2.7.16
```

Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
mordecai = "*"

[requires]
python_version = "2.7"
```

mordecai.py
```
from mordecai import Geoparser
geo = Geoparser()
geo.geoparse("I traveled from Oxford to Ottawa.")
```
---
I've run:
`pyenv version` --> `2.7.16 (set by [WORKING DIR]/.python-version)`
`pipenv install`
`pipenv install mordecai`
`pipenv shell`
`python Mordecai.py` --> 
```
Traceback (most recent call last):
  File "mordecai.py", line 1, in <module>
    from mordecai import Geoparser
  File "[WORKING DIR]/mordecai.py", line 1, in <module>
    from mordecai import Geoparser
ImportError: cannot import name Geoparser
```
_Note: I did get the typical pip install error for tensor flow_ `ERROR: ERROR: Could not find a version that matches wrapt<1.11.0,>=1.10.0,>=1.11.1`

**Comment by thomas-hervey** [comment]
Fixed. Not sure exactly what my problem was, but it may have been that I didn't properly download the Spacy model in my virtualenv, or that my test file was called _mordecai.py_.
